FROM ruby:3.4-slim
RUN apt-get update -qq && apt-get install -y --no-install-recommends build-essential libpq-dev git curl libyaml-dev && rm -rf /var/lib/apt/lists/*
RUN gem install rails -v 8.1.3.1 --no-document
WORKDIR /app
