default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("DB_USER", "books") %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: book_collection_development

test:
  <<: *default
  database: book_collection_test

production:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>
